language: python

python:
  - "3.6"

service:
  -postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database questioner_test;' -U postgres
  export APP_SETTINGS="app.config.TestingConfig"
  export SECRET_KEY="justatest"
  export TEST_DB_URI="dbname='questioner_test'"

script: pytest

after_success:
  - coveralls