language: python

python:
  -"3.6"

service:
  -postgresql

before_install:
  export APP_SETTINGS="app.config.TestingConfig"
  export SECRET_KEY="justatest"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database questioner_test;' -U postgres

after_success:
  - coveralls